require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe FuncionariosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Funcionario. As you add validations to Funcionario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FuncionariosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all funcionarios as @funcionarios" do
      funcionario = Funcionario.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:funcionarios)).to eq([funcionario])
    end
  end

  describe "GET #show" do
    it "assigns the requested funcionario as @funcionario" do
      funcionario = Funcionario.create! valid_attributes
      get :show, {:id => funcionario.to_param}, valid_session
      expect(assigns(:funcionario)).to eq(funcionario)
    end
  end

  describe "GET #new" do
    it "assigns a new funcionario as @funcionario" do
      get :new, {}, valid_session
      expect(assigns(:funcionario)).to be_a_new(Funcionario)
    end
  end

  describe "GET #edit" do
    it "assigns the requested funcionario as @funcionario" do
      funcionario = Funcionario.create! valid_attributes
      get :edit, {:id => funcionario.to_param}, valid_session
      expect(assigns(:funcionario)).to eq(funcionario)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Funcionario" do
        expect {
          post :create, {:funcionario => valid_attributes}, valid_session
        }.to change(Funcionario, :count).by(1)
      end

      it "assigns a newly created funcionario as @funcionario" do
        post :create, {:funcionario => valid_attributes}, valid_session
        expect(assigns(:funcionario)).to be_a(Funcionario)
        expect(assigns(:funcionario)).to be_persisted
      end

      it "redirects to the created funcionario" do
        post :create, {:funcionario => valid_attributes}, valid_session
        expect(response).to redirect_to(Funcionario.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved funcionario as @funcionario" do
        post :create, {:funcionario => invalid_attributes}, valid_session
        expect(assigns(:funcionario)).to be_a_new(Funcionario)
      end

      it "re-renders the 'new' template" do
        post :create, {:funcionario => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested funcionario" do
        funcionario = Funcionario.create! valid_attributes
        put :update, {:id => funcionario.to_param, :funcionario => new_attributes}, valid_session
        funcionario.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested funcionario as @funcionario" do
        funcionario = Funcionario.create! valid_attributes
        put :update, {:id => funcionario.to_param, :funcionario => valid_attributes}, valid_session
        expect(assigns(:funcionario)).to eq(funcionario)
      end

      it "redirects to the funcionario" do
        funcionario = Funcionario.create! valid_attributes
        put :update, {:id => funcionario.to_param, :funcionario => valid_attributes}, valid_session
        expect(response).to redirect_to(funcionario)
      end
    end

    context "with invalid params" do
      it "assigns the funcionario as @funcionario" do
        funcionario = Funcionario.create! valid_attributes
        put :update, {:id => funcionario.to_param, :funcionario => invalid_attributes}, valid_session
        expect(assigns(:funcionario)).to eq(funcionario)
      end

      it "re-renders the 'edit' template" do
        funcionario = Funcionario.create! valid_attributes
        put :update, {:id => funcionario.to_param, :funcionario => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested funcionario" do
      funcionario = Funcionario.create! valid_attributes
      expect {
        delete :destroy, {:id => funcionario.to_param}, valid_session
      }.to change(Funcionario, :count).by(-1)
    end

    it "redirects to the funcionarios list" do
      funcionario = Funcionario.create! valid_attributes
      delete :destroy, {:id => funcionario.to_param}, valid_session
      expect(response).to redirect_to(funcionarios_url)
    end
  end

end
